### ISSUE TITLE
New version based on new openldap image ?

### ISSUE THREAD

**Issue by jrevillard** [tiredofit/docker-openldap-fusiondirectory#10]
Hi,

Could you generate a new version based on the new openldap image please ?
Only the latest tag is up to date.

Best,
Jerome

**Comment by tiredofit** [comment]
Sure, Docker Hub is on a loop right now - It's been building for 3 days out of sequence so I have to let it shake itself out properly to reflect the new changes- I will push manually for you in the next hour and a half.

**Comment by tiredofit** [comment]
New Image pushed `6.4.0` and `latest` that follows latest tiredofit/openldap:6.6.2 build

**Comment by jrevillard** [comment]
Thanks!
