### ISSUE TITLE
ldapsearch works on server which is different that what's set in docker `ENV`

### ISSUE THREAD

**Issue by hxvxt2** [tiredofit/docker-openldap-fusiondirectory#14]
Hello Dave,

I think I had solved this but it came back. The issue appears intermittently and I'm pretty sure I'm missing something obvious. 

After running the `docker-compose` when I try to query the server using ldapsearch it always fails (at least for the server I'm expecting it not to fail for).

`ldapsearch -x -b "dc=CURRENT,dc=local" -H ldap://localhost:389`

```

> # extended LDIF
> #
> # LDAPv3
> # base <dc=CURRENT,dc=com> with scope subtree
> # filter: (objectclass=*)
> # requesting: ALL
> #
> # search result
> search: 2
> result: 32 No such object
> # numResponses: 1

```

However, if I run for this command for an old domain (the one I set my env values with, in the previous runs)

`ldapsearch -x -b "dc=OLD,dc=com" -H ldap://localhost:389`

This one works fine. It looks like even after removing the docker and image and making sure my `docker-compose.yml` file has correct values, my server refuses to reply for the expected domain and always seems to reply on the domain that I had configured previously. 

This happened earlier when I kept querying for the domain `OLD` but the server always kept refusing on that. And queries for `example` domain would run fine (which was my domain from the previous runs). I don't remember how i fixed it, some random combination or `docker -rm` `docker rmi` with `start` `stop` worked. 

But nothing seems to be working this time. What am I missing? 

To be sure, on both the occasions I also ran `env` inside the containers to see what are the actual values for the `domain` inside the container. And to my surprise, these were the same values which were defined in my `docker-compose.yml` (so I'm sure that I'm not passing a wrong yml file during `docker-compose.yml up`) and yet `ldapsearch` refuses to respond on it.

**Comment by tiredofit** [comment]
Actually sounds like you still have your data volumes from your previous install TBH.

Head inside your container and run `slapcat -n1 | less` and the first few lines are going to show your BaseDN and also the Created time. 

I'm not sure if you are using the example docker-compose.yml - but if so, you would want to `rm -rf data` before starting fresh.

**Comment by hxvxt2** [comment]
Aahaa! I see. Docker creates folders on the host machine that act as Volume for the container. Cleaned up the data folder and it worked. 

Thanks Dave!
