### ISSUE TITLE
Invalid dn (cn=<READONLY_USER_USER>,dc=example,dc=com)

### ISSUE THREAD

**Issue by mjmucha** [tiredofit/docker-openldap-fusiondirectory#19]
Hello again!

So after testing [this fix](https://github.com/tiredofit/docker-fusiondirectory/issues/29#issuecomment-649709111) on clean installation i get the following error (with `DEBUG_MODE`) when the OpenLDAP container starts:

```
adding new entry "cn=<READONLY_USER_USER>,dc=example,dc=com"
5ef4dfdf conn=1005 op=1 do_add: invalid dn (cn=<READONLY_USER_USER>,dc=example,dc=com)
5ef4dfdf conn=1005 op=1 RESULT tag=105 err=34 text=invalid DN
ldap_add: Invalid DN syntax (34)
	additional info: invalid DN
5ef4dfdf conn=1005 op=2 UNBIND
5ef4dfdf conn=1005 fd=12 closed
[cont-init.d] 10-openldap: exited 34.
```

Any Ideas?

**Comment by tiredofit** [comment]
Darnit. Missed that one.  FWIW since you areusing fusion directory I would skip read only users from the image entirely and use the FD DSA plugin instead.

I will push a patch shortly.

**Comment by tiredofit** [comment]
Thanks for spotting this - I moved a view environment variables around and missed this entirely. New tag `7.0.1` should get you going.

**Comment by mjmucha** [comment]
I have to thank for the quick response :) Will test it now

**Comment by mjmucha** [comment]
So this specific error message is now fixed but somehow the container refused to start. However i cant seem to find the cause of it.

Here a part of the log:
```
adding new entry "cn=readonly,dc=snh,dc=nrw"
5ef5b42d conn=1005 op=1 ADD dn="cn=readonly,dc=snh,dc=nrw"
5ef5b42d conn=1005 op=1 RESULT tag=105 err=32 text=
ldap_add: No such object (32)
5ef5b42d conn=1005 op=2 UNBIND

5ef5b42d conn=1005 fd=12 closed
[cont-init.d] 10-openldap: exited 32.
[cont-init.d] 99-container: executing...
+ PROCESS_NAME=container
+ var_false FALSE
+ '[' FALSE = FALSE ']'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
**********************************************************************************************************************
**********************************************************************************************************************
****                                                                                                              ****
****       ERROR - Some initialization scripts haven't completed - All services are now halted                    ****
****             - The following scripts in '/etc/cont-init.d' did not pass their completion check                ****
****                                                                                                              ****
**********************************************************************************************************************
**********************************************************************************************************************

10-openldap


**********************************************************************************************************************
**********************************************************************************************************************
****                                                                                                              ****
****       This could have happened for a variety of reasons. Please make sure you have followed the README       ****
****       relating to this image and have proper configuration such as environment variables and volumes set     ****
****                                                                                                              ****
****       If you feel that you have encountered a bug, please submit an issue on the revision control system     ****
****       and provide full debug logs by setting the environment variable 'DEBUG_MODE=TRUE'                      ****
****                                                                                                              ****
**********************************************************************************************************************
**********************************************************************************************************************
[cont-init.d] 99-container: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by tiredofit** [comment]
OK this is enough for me to work with - How bizarre. I wonder if READONLY_USER has been broken for a while now. I'll head to testing this out on my end and have a response within a few hours.

**Comment by tiredofit** [comment]
I see where the problem is. Going to rearrange the point where the DSA user is being added and run it through a couple of different tests. If readonly user is enabled I actually create it twice if you are using fusiondirectory, so I'm going to change that and only have it added once Fusiondirectory schemas are being installed. Should have a fix shortly.

**Comment by tiredofit** [comment]
Tagged as `7.0.2` or `latest` - Thanks for finding this.

**Comment by mjmucha** [comment]
So i tried now to test the current version. But again it wont start. Here is the log:
```
[cont-init.d] 10-openldap: executing... 
[NOTICE] ** [openldap] Setting up directories
[NOTICE] ** [openldap] Configuring OpenLDAP server
[WARN] ** [openldap] First time install detected
[NOTICE] ** [openldap] Using NIS schema type
[NOTICE] ** [openldap] Converting schemas to LDIF
[NOTICE] ** [openldap] Adding converted schemas
[NOTICE] ** [openldap] Setting Security and ACLs
[NOTICE] ** [openldap] Add bootstrap LDIFs
[NOTICE] ** [openldap] Starting TLS configuration. Please wait
[NOTICE] ** [openldap] Certificates: DH Param - Creating /certs//dhparam.pem
[cont-init.d] 10-openldap: exited 80.
[cont-init.d] 99-container: executing... 
**********************************************************************************************************************
**********************************************************************************************************************
****                                                                                                              ****
****       ERROR - Some initialization scripts haven't completed - All services are now halted                    ****
****             - The following scripts in '/etc/cont-init.d' did not pass their completion check                ****
****                                                                                                              ****
**********************************************************************************************************************
**********************************************************************************************************************
```

**Comment by tiredofit** [comment]
Thank you that's a new one. Can you post your docker-compose.yml either here or send privately to my email?

**Comment by mjmucha** [comment]
Here is my docker-compose. Only exchanged domain specific informations.

[docker-compose.yml.zip](https://github.com/tiredofit/docker-openldap-fusiondirectory/files/4853396/docker-compose.yml.zip)

**Comment by tiredofit** [comment]
Thanks. I think your TLS CIPHER_LIST env var is requesting things that are not available via LDAP. Looking at the error `TLS: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match ssl/ssl_lib.c:2558` is my hint and then noting your docker-compose is different from the defaults. The image doesn't restrict what ciphers you use, but I'm wondering if this is an openldap limitation itself.

Maybe try changing your cipher list  and experimenting as to which one is breaking it?

**Comment by mjmucha** [comment]
That is weird because I used the same cipher list before with an working LDAP/Fusion container.

**Comment by tiredofit** [comment]
Sure, not questioning that its a good cipher list - Something is not sticking properly with it. Potentially wrap it with quotes? 
While I touched some things like cert locations I haven't touched the TLS CIPHER LIST in a very long time (which does deserve a review for defaults) so I'm at a loss here as to why it would be failing. I do know you just can't use the same ciphers say for nginx/traefik/postfix in LDAP. 

Have a peek at https://access.redhat.com/articles/1482663 and see if yours match up.

**Comment by mjmucha** [comment]
So with a cipher list from your very helpful link the container starts. But for me it is still weird, that the cipher list i used before did work some months ago.

Anyway thank you **very** much for you help! I can now close this issue. (Well I have another one (minor) incoming...)
