### ISSUE TITLE
LDAP Ports not exposed by default

### ISSUE THREAD

**Issue by smacz42** [tiredofit/docker-openldap-fusiondirectory#2]
I understand that the `ports` directive in the docker-compose file exposes them on the host. However, for instances where this image is run on the same host as the corresponding [docker-fusiondirectory](https://github.com/tiredofit/docker-fusiondirectory) container, the docker-compose file has to specify that those two ports be exposed.

Shouldn't ports `389` and `636` be exposed by default?

**Comment by tiredofit** [comment]
You are right, after all this time (years!) I have missed it. My usage case is likely much different than others. I am going to expose them in the [tiredofit/openldap](https://github.com/tiredofit/docker-openldap) image instead and rebuild existing image. Thanks for this.

**Comment by tiredofit** [comment]
New commit pushed to match base image. Should be on Dockerhub in the next few hours.
