### ISSUE TITLE
three-level domain fails

### ISSUE THREAD

**Issue by smacz42** [tiredofit/docker-openldap-fusiondirectory#3]
https://github.com/tiredofit/docker-openldap-fusiondirectory/blob/ce1c025cde38f3248838f2d6d45b523deebd54e7/install/assets/custom-scripts/001-install-fusiondirectory.sh#L21-L42

I have a subdomain that I am trying to implement this at - `trans.hobbithole.blue`, and when these lines are reached, line 28 correctly assigns it, but then it gets reassigned at line 40 incorrectly. It ends up being "dc=trans,dc=blue". This is then the suffix that is used to build the directory structure.

It almost seems like these two loops are doing the same thing with setting the `BASE_DN` variable. 

Actually, the more I read through this, the more confused I get. `SUFFIX` isn't used anywhere else, so it has to just be a way to compute what the `BASE_DN` is. `ROOT` is used elsewhere, but that should be easy enough to get from the `BASE_DN`.

If I were to write this, I would have chosen the implementation at lines 21-28, as it's clearer, cleaner, and works for multiple subdomains. I don't see why `BASE_DN` needs to be reset below.

**Comment by tiredofit** [comment]
Nice as well. I refactored this a few months ago and must have missed this and not caught multi subdomain names. Did you want to submit a PR for this? Otherwise I'll be about 10 days away from getting to this one as I'm in the middle of a monster move.

**Comment by tiredofit** [comment]
It looks as if there is a PR already on the docker-openldap repository for just this:
https://github.com/tiredofit/docker-openldap/pull/3  - Is this what you are after? If so I will merge and create a release.

**Comment by smacz42** [comment]
Hah, yes, that appears to be what I was describing. Merging that should take care of the issue I was running into.

On March 21, 2019 11:53:17 PM EDT, Dave Conroy <notifications@github.com> wrote:
>It looks as if there is a PR already on the docker-openldap repository
>for just this:
>https://github.com/tiredofit/docker-openldap/pull/3  - Is this what you
>are after? If so I will merge and create a release.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tiredofit/docker-openldap-fusiondirectory/issues/3#issuecomment-475485390

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by smacz42** [comment]
Actually, after thinking about it for a minute, you are using the `ROOT` variable other places, so I might have to add that to the PR. Let me look at this when I have some time.

**Comment by smacz42** [comment]
This should fix the problem of the `ROOT` variable being unassigned after the other PR is merged.

**Comment by smacz42** [comment]
Well, the changes upstream haven't been pulled in, so I'm experiencing the same problem.

Additionally, it looks like 001-install-fusiondirectory.sh is failing to be run. And when I run it manually, there are many errors about not being able to connect to the ldap backend. I can only presume this is because it is not running.

**Comment by tiredofit** [comment]
I will build it locally on my system in a few hours and push to docker hub under the tag of :develop to help you with this.
