### ISSUE TITLE
addding a new server pair - replication script is not working

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-openldap-fusiondirectory#40]
### Summary

the replication data are not created properly

### Steps to reproduce
create a new ldap server, replication parameters like: 

```
- ENABLE_REPLICATION=TRUE
    - WAIT_FOR_REPLICAS=false
    - REPLICATION_SAFETY_CHECK=TRUE
    - REPLICATION_CONFIG_SYNCPROV=binddn="cn=admin,cn=config" bindmethod=simple credentials="pw!" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1
    - REPLICATION_DB_SYNCPROV=binddn="cn=admin,dc=blabla,dc=de" bindmethod=simple credentials="pw!" searchbase="dc=elternserver,dc=de" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1
    - REPLICATION_HOSTS=ldap://ldap1.blabla.de ldap://ldap4.blabla.de ldap://ldap2.blabla.de
 ```

### generated script /assets/slapd/config/replication/replication-enable.ldif : 
```
...
# Add sync replication on config
dn: olcDatabase={0}config,cn=config
changetype: modify
add: olcSyncRepl
olcSyncRepl: rid=001 provider=ldap://ldap1.blabla.de binddn="cn=config" bindmethod=simple credentials="pw!" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 filter="(!(objectclass=olcGlobal))"
<REPLICATION_HOSTS_CONFIG_SYNC_REPL>
...
```
instead the < REPL ... line I'd like to see the other servers

**Comment by tiredofit** [comment]
Interesting. It's been a while since any actual work has been done on these repositories they just seem to work for me. Can you confirm you are using 2.6-1.4 releases?

**Comment by joergmschulz** [comment]
yes, latest and greatest.

image: tiredofit/openldap-fusiondirectory:2.6-1.4-latest

**Comment by tiredofit** [comment]
OK Thanks, this is quite surprising - Perhaps something in the source tree has snuck in. To review on Monday..

**Comment by joergmschulz** [comment]
not a docker.io build issue. It also happens when I use
``` 
image: tiredofit/openldap-fusiondirectory:2.6-1.4-latest
    build:
       context: https://github.com/tiredofit/docker-openldap-fusiondirectory.git#2.6-1.4-7.6.5
```

my memory is short. We already had that in https://github.com/tiredofit/docker-openldap/issues/67 but the release you fixed that in doesn't exist any longer (7.4.2)

**Comment by joergmschulz** [comment]
Yes, still and again: 
<REPLICATION_HOSTS_DB_SYNC_REPL>
versus 
{{REPLICATION_HOSTS_DB_SYNC_REPL}} 
in install/assets/defaults/10-openldap and /assets/slapd/config/replication/replication-enable.ldif. Which one is correct? < or {{ ? 
it's to be handled in the openldap repo, not here.

**Comment by tiredofit** [comment]
I think I found it. And yes, in the upstream openldap repo I just pushed a new commit that should resolve that. I am digging a bit deeper.

**Comment by joergmschulz** [comment]
This has been properly fixed by https://github.com/tiredofit/docker-openldap-fusiondirectory/commit/a813c9a5ec2ac53c3d09ec1e6e6730cf5be7c21c // not yet in the docker release, but hoping for the best to find it there. 

Tested in my environment, replication works perfectly again. Thank you very much.
