### ISSUE TITLE
Add attribute to activate MemberOf

### ISSUE THREAD

**Issue by Manuki-San** [tiredofit/docker-openldap-fusiondirectory#7]
This is a request to support MemberOf, switchable from an environment variable

**Comment by tiredofit** [comment]
Hi there, memberOf should be automatically enabled by default.

Upon initial install I import the following LDIF: https://github.com/tiredofit/docker-openldap/blob/master/install/assets/slapd/config/bootstrap/ldif/03-memberOf.ldif

Recursive / Groups in Groups also is enabled, however the only libraries that I have found that support it nicely so far is the perl-ldap library.

**Comment by Manuki-San** [comment]
Got it. Thank you.
