### ISSUE TITLE
install fusiondirectory, won't work if domain contain a Subdomain

### ISSUE THREAD

**Issue by NokiDev** [tiredofit/docker-openldap-fusiondirectory#8]
There is an issue with the parsing of DOMAIN env variable if the domain contains a subdomain
even if BASE_DN env is set explicitely.

e.g : 
     awesome.domain.tld
results in dc=awesome,dc=tld

**Comment by tiredofit** [comment]
Strange, we solved this a few months ago on the base image (tiredofit/openldap) - Can you try to see if you have the same issues with just that image instead of the tiredofit/openldap-fusiondirectory ? If so something is broken with the build system and I can start to repair that.

**Comment by NokiDev** [comment]
Wow thanks for the fast response. 

The issue is right there 
line 36-41 of 001-install-fusiondirectory.sh
```
if [ "x${SUFFIX}" = x ] ; then
       SUFFIX="dc=${elem}"
       ROOT="${elem}"
else
       BASE_DN="${SUFFIX},dc=${elem}"
fi
```
BASE_DN isn't append with each iteration. 
so it results in the suffix and last element of the domain name.

BASE_DN should be concat with itself and add the current element.

**Comment by tiredofit** [comment]
Thanks again!
